// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-G1hdvGp21pN1-YbcHW-2YHLrxWXPTA',
    appId: '1:862139598195:web:be55391ae9627374eeb106',
    messagingSenderId: '862139598195',
    projectId: 'tasks-53290',
    authDomain: 'tasks-53290.firebaseapp.com',
    storageBucket: 'tasks-53290.appspot.com',
    measurementId: 'G-9CRLMYZJ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuSKpVzGnJdcrqmhijkVaaGIuzFQqo4VU',
    appId: '1:862139598195:android:ac0e6ea7328edbabeeb106',
    messagingSenderId: '862139598195',
    projectId: 'tasks-53290',
    storageBucket: 'tasks-53290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2dsjXSZb7FpoA5SyCObzfTrpdMvHPbvs',
    appId: '1:862139598195:ios:6bcf1b82ce90cacaeeb106',
    messagingSenderId: '862139598195',
    projectId: 'tasks-53290',
    storageBucket: 'tasks-53290.appspot.com',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2dsjXSZb7FpoA5SyCObzfTrpdMvHPbvs',
    appId: '1:862139598195:ios:18108316bdf64d85eeb106',
    messagingSenderId: '862139598195',
    projectId: 'tasks-53290',
    storageBucket: 'tasks-53290.appspot.com',
    iosBundleId: 'com.example.tasks.RunnerTests',
  );
}
